/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GlassRouteImport } from './routes/glass'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilesIndexRouteImport } from './routes/profiles.index'
import { Route as ProfilesSlugRouteImport } from './routes/profiles.$slug'
import { Route as ProductsBrendorsRouteImport } from './routes/products.brendors'
import { Route as ConfiguratorTypeIdRouteImport } from './routes/configurator.$typeId'

const GlassRoute = GlassRouteImport.update({
  id: '/glass',
  path: '/glass',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesSlugRoute = ProfilesSlugRouteImport.update({
  id: '/profiles/$slug',
  path: '/profiles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBrendorsRoute = ProductsBrendorsRouteImport.update({
  id: '/products/brendors',
  path: '/products/brendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguratorTypeIdRoute = ConfiguratorTypeIdRouteImport.update({
  id: '/configurator/$typeId',
  path: '/configurator/$typeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/glass': typeof GlassRoute
  '/configurator/$typeId': typeof ConfiguratorTypeIdRoute
  '/products/brendors': typeof ProductsBrendorsRoute
  '/profiles/$slug': typeof ProfilesSlugRoute
  '/profiles/': typeof ProfilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/glass': typeof GlassRoute
  '/configurator/$typeId': typeof ConfiguratorTypeIdRoute
  '/products/brendors': typeof ProductsBrendorsRoute
  '/profiles/$slug': typeof ProfilesSlugRoute
  '/profiles': typeof ProfilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/glass': typeof GlassRoute
  '/configurator/$typeId': typeof ConfiguratorTypeIdRoute
  '/products/brendors': typeof ProductsBrendorsRoute
  '/profiles/$slug': typeof ProfilesSlugRoute
  '/profiles/': typeof ProfilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contacts'
    | '/glass'
    | '/configurator/$typeId'
    | '/products/brendors'
    | '/profiles/$slug'
    | '/profiles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/glass'
    | '/configurator/$typeId'
    | '/products/brendors'
    | '/profiles/$slug'
    | '/profiles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contacts'
    | '/glass'
    | '/configurator/$typeId'
    | '/products/brendors'
    | '/profiles/$slug'
    | '/profiles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactsRoute: typeof ContactsRoute
  GlassRoute: typeof GlassRoute
  ConfiguratorTypeIdRoute: typeof ConfiguratorTypeIdRoute
  ProductsBrendorsRoute: typeof ProductsBrendorsRoute
  ProfilesSlugRoute: typeof ProfilesSlugRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/glass': {
      id: '/glass'
      path: '/glass'
      fullPath: '/glass'
      preLoaderRoute: typeof GlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof ProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$slug': {
      id: '/profiles/$slug'
      path: '/profiles/$slug'
      fullPath: '/profiles/$slug'
      preLoaderRoute: typeof ProfilesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/brendors': {
      id: '/products/brendors'
      path: '/products/brendors'
      fullPath: '/products/brendors'
      preLoaderRoute: typeof ProductsBrendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurator/$typeId': {
      id: '/configurator/$typeId'
      path: '/configurator/$typeId'
      fullPath: '/configurator/$typeId'
      preLoaderRoute: typeof ConfiguratorTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactsRoute: ContactsRoute,
  GlassRoute: GlassRoute,
  ConfiguratorTypeIdRoute: ConfiguratorTypeIdRoute,
  ProductsBrendorsRoute: ProductsBrendorsRoute,
  ProfilesSlugRoute: ProfilesSlugRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
